# Generated by Django 5.1.5 on 2025-01-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_prestamo_created_prestamo_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
