# Generated by Django 4.2.4 on 2023-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=15)),
                ('ISBN', models.CharField(max_length=13)),
                ('numero_Inventario', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
