# Generated by Django 4.2.7 on 2023-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(upload_to='libros'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
