# Generated by Django 4.2.7 on 2023-11-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_created_alter_libro_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
