# Generated by Django 4.2.7 on 2023-11-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_created_alter_libro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
