# Generated by Django 4.2.7 on 2023-11-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libro_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='created',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='updated',
        ),
    ]
