# Generated by Django 4.2.4 on 2023-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_libro_options_libro_created_libro_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={},
        ),
        migrations.AlterField(
            model_name='libro',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
