# Generated by Django 4.2.4 on 2023-11-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_alter_libro_options_alter_libro_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('numero_de_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('libro_solicitado', models.CharField(max_length=60)),
            ],
        ),
    ]
