# Generated by Django 5.1.5 on 2025-01-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_delete_prestamo_alter_libro_autor_alter_libro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
